---
- name: Install Docker on Ubuntu and Amazon Linux
  hosts: all
  become: yes
  tasks:
    - name: Install Docker on Ubuntu
      when: ansible_facts['os_family'] == "Debian"
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker on Amazon Linux
      when: ansible_facts['os_family'] == "RedHat"
      yum:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes
